---
- name: install system
  hosts: localhost
  connection: local
  become: yes
  vars:
    user: test # change
    group: test # change
  roles:
    - name: base
      tags: base
    - name: alias
      tags: alias
    - name: ssh
      tags: ssh
