---
- name: install system
  hosts: localhost
  connection: local
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ lookup('env', 'USER') }}"
    - base
    - role: java
      vars:
        versions: ["8", "11", "17"]
        default: "17"
    - role: maven
      vars:
        versions: ["3.8.4", "3.6.3", "3.5.4"]
        default: "3.8.4"
    - role: docker
      become: true
