---
# install collections via ansible-galaxy install -r <this file>
roles:
  - name: gantsign.oh-my-zsh
    version: 2.4.0
  - name: gantsign.java
    version: 10.0.0
  - name: gantsign.maven
    version: 5.6.3