alias n=nomad

alias ng='n agent'
alias ngc='ng -config'
alias ngd='ng -dev'

alias nj='n job'
alias njs='nj status'
alias njr='nj run'
alias njri='njr -check-index'
alias nji='nj init'
alias njp='nj plan'
alias njo='nj promote'
alias njd='nj deployments'
alias njt='nj stop'

alias na='n alloc'
alias nas='ns status'

alias nd='n deployment'
alias ndl='nd list'
alias ndf='nd fail'
alias ndp='nd promote'
alias ndr='nd resume'
alias nds='nd status'
alias ndo='nd pause'
alias ndu='nd unblock'

alias no='n operator'
alias noa='no autopilot'
alias nod='no debug'
alias nokg='no keygen'
alias nokr='no keyring'
alias nor='no raft'
alias nos='no snapshot'
